dist: trusty
sudo: false
language: minimal
env:
   global:
    - MAVEN_OPTS="-Dformatter.skip=true -Dsurefire.useFile=false -Dmaven.artifact.threads=256 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dinvoker.streamLogs=false -Drmannibucau.travis.dumpOnLog=false"
    - SKIP_OPTS="-Dspotless.apply.skip=true -Dcheckstyle.skip=true -Drat.skip=true -DskipTests -Dinvoker.skip=true -Ptravis -Dmaven.ext.class.path=/tmp/maven-travis-output-1.0.0.jar"
    - DEPLOY_OPTS="$SKIP_OPTS --batch-mode -Possrh -Prelease"
    - BUILD_ARGS="clean install -B -q -e -Possrh -Ptravis -Prelease -Pdoc-gen -Dgpg.skip=true -Ptravis -Dmaven.ext.class.path=/tmp/maven-travis-output-1.0.0.jar"
before_cache:
  - rm -Rf $HOME/.m2/repository/org/talend/sdk/component
  - find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf
cache:
  timeout: 1000
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache/talend"
  - "$HOME/.cache/yarn"
  - "$HOME/build/Talend/component-runtime/component-starter-server/.node"
  - "$HOME/build/Talend/component-runtime/component-starter-server/.cache"
  - "$HOME/build/Talend/component-runtime/component-starter-server/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/component-tools/.node"
  - "$HOME/build/Talend/component-runtime/component-tools/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/component-tools-webapp/.node"
  - "$HOME/build/Talend/component-runtime/component-tools-webapp/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/documentation/.node"
  - "$HOME/build/Talend/component-runtime/documentation/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/talend-component-kit-intellij-plugin/.cache"
  - "$HOME/build/Talend/component-runtime/.ci-cache"
  - "$HOME/build/Talend/component-runtime/.blackduck/tools"
notifications:
  email: false
  slack:
    on_pull_requests: true
    secure: MS3jwqvACvjLAa2pT8OdmylmqK0N+zMg7URmatJYHa+HXTr3dTlKNVSCDTUGc5OIYUhzca15SYAtXjUMYcyJ5UQETE6bxS5995GBbTsErEOFDYIZU5coFz1/21+b0E72QDHKOVWntSPVujNB2ZA8aJVLgpmdSC0t83b85Nds9R0Skaag8ehkVGWw57MI7xy+Bo3CXkLS3A8Mjucy1Ht7hgtrlE+hzBMVZeJbLVWZkYD1p0QguXaSD7Ub3Uab7sDiINZv4DDZSGz7lkv0IUh8bQhsfrwFKbks2TtavcuQcbHIKXG00LZpTPLfXIgGXD6hGtD4WgCbfXacsri+yoiQbE8oVXriTWCOusXTjQd2RgtKbUPOOKSAQ4BW+yXHu8exb+tqx87onpGI9w339BY/zCUbnMJruKWVO3G0LISg1b1AkPC+s6PCi8T3PrXV0o7/53hSDM1xmS0ZO8BgqsvqorYDiun11+yTl+OZNGcm85dyLVKonzuG3o+2EiqI8nfrxK11S2c+37BLJSrgHRhmV0VESW1JF0VaSZOUCCO2KkWl7tNTIYkfG0nqdq6q1E+uo5Wz61Wc6oqcS9MCvh133bqDlK3ecQ4h7cBeD3iZdT1+wbRRnOJ/sGtCrB2pvzWC9rkwx5UcS8m7TR3EdXD9hllhfBtR9aCGtRx/p4YwJfo=

before_install: chmod +x ./.travis/*.sh && source ./.travis/install.sh
install: true

jobs:
  include:
    # PR profile
    - stage: pullrequest_build
      script: travis_wait 50 mvn $BUILD_ARGS

    # master profile
    - stage: master_build
      env:
      - STEP=Build OpenJDK 8 JVM
      script: mvn $BUILD_ARGS

    - stage: master_build
      env:
      - STEP=Build OpenJDK 11 JVM
      - BUILD_JAVA_VERSION=11
      script: mvn $BUILD_ARGS

    - stage: master_build
      env:
      - STEP=Deploy Artifacts
      before_script: ./.travis/setup_keys.sh
      script: travis_wait 50 mvn clean deploy -e -q $DEPLOY_OPTS

    - stage: master_build
      env:
      - STEP=Update Documentation
      script:
      - MAVEN_OPTS="$MAVEN_OPTS -Xverify:none" travis_wait 50 mvn clean install -e -q -Pdoc-gen -Pgh-pages -Dgpg.skip=true -Dtalend.github.cache=true $DEPLOY_OPTS
      - cd documentation && travis_wait 50 mvn clean verify pre-site -e -Dwebhost.ftphost=$WEBHOST_FTPPHOST -Pgh-pages -Dgpg.skip=true $SKIP_OPTS && cd -

    - stage: master_build
      env:
      - STEP=Docker Server Deployment
      before_script: ./.travis/setup_keys.sh
      script: travis_wait 50 mvn clean install -pl images/component-server-image -am $DEPLOY_OPTS && cd images/component-server-image && mvn clean install jib:build@build -Dtalend.server.image.registry=registry.hub.docker.com/ $DEPLOY_OPTS

    - stage: master_build
      env:
      - STEP=Docker Server Proxy Deployment
      before_script: ./.travis/setup_keys.sh
      script: travis_wait 50 mvn clean install -pl images/component-server-vault-proxy-image -am $DEPLOY_OPTS && cd images/component-server-vault-proxy-image && mvn clean install jib:build@build -Dtalend.server.image.registry=registry.hub.docker.com/ $DEPLOY_OPTS

    - stage: master_build
      env:
      - STEP=Sonatype Audit
      script: travis_wait 50 mvn clean install -B -q -e $SKIP_OPTS && travis_wait 50 mvn ossindex:audit -B

    - stage: master_build
      env:
      - STEP=SourceClear Audit
      script: travis_wait 50 ./travis/source-clear.sh

stages:
  - name: master_build
    if: branch = master AND type != pull_request
  - name: pullrequest_build
    if: type = pull_request
