language: java
jdk:
- oraclejdk8
env:
  global:
    - MAVEN_OPTS="-Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss -Dinvoker.streamLogs=false -Dhub-detect.skip=true -Dsurefire.useFile=false"
before_cache:
  - rm -Rf $HOME/.m2/repository/org/talend/sdk/component
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache/yarn"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-form/component-form-demo/.node"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-form/component-form-demo/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-starter-server/.node"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-starter-server/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-tools/.node"
  - "$HOME/build/Talend/component-runtime/component-runtime/component-tools/src/main/frontend/node_modules"
  - "$HOME/build/Talend/component-runtime/component-studio-integration/.p2localrepository"
  - "$HOME/build/Talend/component-runtime/component-starter-server/.cache"
  - "$HOME/build/Talend/component-runtime/.blackduck"
notifications:
  email: false
  slack:
    on_pull_requests: true
    secure: MS3jwqvACvjLAa2pT8OdmylmqK0N+zMg7URmatJYHa+HXTr3dTlKNVSCDTUGc5OIYUhzca15SYAtXjUMYcyJ5UQETE6bxS5995GBbTsErEOFDYIZU5coFz1/21+b0E72QDHKOVWntSPVujNB2ZA8aJVLgpmdSC0t83b85Nds9R0Skaag8ehkVGWw57MI7xy+Bo3CXkLS3A8Mjucy1Ht7hgtrlE+hzBMVZeJbLVWZkYD1p0QguXaSD7Ub3Uab7sDiINZv4DDZSGz7lkv0IUh8bQhsfrwFKbks2TtavcuQcbHIKXG00LZpTPLfXIgGXD6hGtD4WgCbfXacsri+yoiQbE8oVXriTWCOusXTjQd2RgtKbUPOOKSAQ4BW+yXHu8exb+tqx87onpGI9w339BY/zCUbnMJruKWVO3G0LISg1b1AkPC+s6PCi8T3PrXV0o7/53hSDM1xmS0ZO8BgqsvqorYDiun11+yTl+OZNGcm85dyLVKonzuG3o+2EiqI8nfrxK11S2c+37BLJSrgHRhmV0VESW1JF0VaSZOUCCO2KkWl7tNTIYkfG0nqdq6q1E+uo5Wz61Wc6oqcS9MCvh133bqDlK3ecQ4h7cBeD3iZdT1+wbRRnOJ/sGtCrB2pvzWC9rkwx5UcS8m7TR3EdXD9hllhfBtR9aCGtRx/p4YwJfo=
before_install:
- chmod +x ./.travis/setup_keys.sh && ./.travis/setup_keys.sh
install: chmod +x ./.travis/install.sh && ./.travis/install.sh
script: node .travis/heartbeat.js mvn clean install -e --batch-mode -q -ff --settings .travis/settings.xml -Possrh -Ptravis -Prelease -Dgpg.skip=true
after_success:
- chmod +x ./.travis/after_success.sh && ./.travis/after_success.sh
