apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: talend-registry
  containers:
    - name: main
      image: 'artifactory.datapwn.com/tlnd-docker-dev/talend/common/tsbi/jdk11-svc-springboot-builder:2.9.18-2.4-20220104141654'
      command: [ cat ]
      tty: true
      volumeMounts: [
        { name: docker, mountPath: /var/run/docker.sock },
        { name: efs-jenkins-component-runtime-m2, mountPath: /root/.m2/repository },
        { name: efs-jenkins-component-runtime-download, mountPath: /tmp/download },
        { name: dockercache, mountPath: /root/.dockercache }
      ]
      resources: { requests: { memory: 3G, cpu: '2' }, limits: { memory: 8G, cpu: '2' }}
  volumes:
    - name: docker
      hostPath: { path: /var/run/docker.sock }
    - name: dockercache
      hostPath: { path: /tmp/jenkins/tdi/docker }
    - name: efs-jenkins-component-runtime-m2
      persistentVolumeClaim:
        claimName: efs-jenkins-component-runtime-m2
    - name: efs-jenkins-component-runtime-download
      persistentVolumeClaim:
        claimName: efs-jenkins-component-runtime-download